/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Archives: typeof import('./theme/components/archives/index.vue')['default']
    ArchivesList: typeof import('./theme/components/archives/ArchivesList.vue')['default']
    ArchivesPage: typeof import('./theme/components/archives/ArchivesPage.vue')['default']
    Count: typeof import('./theme/components/count/index.vue')['default']
    CustomLink: typeof import('./theme/components/global/CustomLink.vue')['default']
    CustomNavBar: typeof import('./theme/components/layout/CustomNavBar.vue')['default']
    HomePageContent: typeof import('./theme/components/home/HomePageContent.vue')['default']
    HomeStatsSection: typeof import('./theme/components/home/HomeStatsSection.vue')['default']
    HomeTechSection: typeof import('./theme/components/home/HomeTechSection.vue')['default']
    InlinePlayground: typeof import('./theme/components/global/playground/InlinePlayground.vue')['default']
    LinkItem: typeof import('./theme/components/link/LinkItem.vue')['default']
    LinkList: typeof import('./theme/components/link/LinkList.vue')['default']
    LinkPage: typeof import('./theme/components/LinkPage.vue')['default']
    PlaygroundWithVariants: typeof import('./theme/components/global/playground/PlaygroundWithVariants.vue')['default']
    SelectorVariants: typeof import('./theme/components/global/playground/SelectorVariants.vue')['default']
    TagsList: typeof import('./theme/components/tags/TagsList.vue')['default']
    TagsPageContent: typeof import('./theme/components/tags/TagsPageContent.vue')['default']
    TagsPageHeader: typeof import('./theme/components/tags/TagsPageHeader.vue')['default']
    TagsSearchBox: typeof import('./theme/components/tags/TagsSearchBox.vue')['default']
    TagsStats: typeof import('./theme/components/tags/TagsStats.vue')['default']
    TagsTips: typeof import('./theme/components/tags/TagsTips.vue')['default']
    TalkDate: typeof import('./theme/components/TalkDate/index.vue')['default']
    TalkItem: typeof import('./theme/components/talk/TalkItem.vue')['default']
    TalkList: typeof import('./theme/components/talk/TalkList.vue')['default']
    VPLink: typeof import('./theme/components/layout/VPLink.vue')['default']
  }
}
