/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArchivesList: typeof import('./.vitepress/theme/components/archives/ArchivesList.vue')['default']
    ArchivesPage: typeof import('./.vitepress/theme/components/archives/ArchivesPage.vue')['default']
    Count: typeof import('./.vitepress/theme/components/count/index.vue')['default']
    CustomCard: typeof import('./.vitepress/theme/components/common/CustomCard.vue')['default']
    CustomLink: typeof import('./.vitepress/theme/components/global/CustomLink.vue')['default']
    EmptyState: typeof import('./.vitepress/theme/components/common/EmptyState.vue')['default']
    HomePageContent: typeof import('./.vitepress/theme/components/home/HomePageContent.vue')['default']
    HomeStatsSection: typeof import('./.vitepress/theme/components/home/HomeStatsSection.vue')['default']
    HomeTechSection: typeof import('./.vitepress/theme/components/home/HomeTechSection.vue')['default']
    InlinePlayground: typeof import('./.vitepress/theme/components/global/playground/InlinePlayground.vue')['default']
    LinkItem: typeof import('./.vitepress/theme/components/link/LinkItem.vue')['default']
    LinkList: typeof import('./.vitepress/theme/components/link/LinkList.vue')['default']
    LinkPage: typeof import('./.vitepress/theme/components/link/LinkPage.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NRow: typeof import('naive-ui')['NRow']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    PageHeader: typeof import('./.vitepress/theme/components/common/PageHeader.vue')['default']
    PlaygroundWithVariants: typeof import('./.vitepress/theme/components/global/playground/PlaygroundWithVariants.vue')['default']
    SelectorVariants: typeof import('./.vitepress/theme/components/global/playground/SelectorVariants.vue')['default']
    StatsCard: typeof import('./.vitepress/theme/components/common/StatsCard.vue')['default']
    TagsList: typeof import('./.vitepress/theme/components/tags/TagsList.vue')['default']
    TagsPageContent: typeof import('./.vitepress/theme/components/tags/TagsPageContent.vue')['default']
    TagsPageHeader: typeof import('./.vitepress/theme/components/tags/TagsPageHeader.vue')['default']
    TagsSearchBox: typeof import('./.vitepress/theme/components/tags/TagsSearchBox.vue')['default']
    TagsStats: typeof import('./.vitepress/theme/components/tags/TagsStats.vue')['default']
    TagsTips: typeof import('./.vitepress/theme/components/tags/TagsTips.vue')['default']
    TalkItem: typeof import('./.vitepress/theme/components/talk/TalkItem.vue')['default']
    TalkList: typeof import('./.vitepress/theme/components/talk/TalkList.vue')['default']
    TalksPage: typeof import('./.vitepress/theme/components/talk/TalksPage.vue')['default']
  }
}
