/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Archives: typeof import('./.vitepress/theme/components/Archives/index.vue')['default']
    ArchivesList: typeof import('./.vitepress/theme/components/Archives/ArchivesList.vue')['default']
    Count: typeof import('./.vitepress/theme/components/count/index.vue')['default']
    InlinePlayground: typeof import('./.vitepress/theme/components/global/playground/InlinePlayground.vue')['default']
    LinkItem: typeof import('./.vitepress/theme/components/Link/LinkItem.vue')['default']
    LinkList: typeof import('./.vitepress/theme/components/Link/LinkList.vue')['default']
    LinkPage: typeof import('./.vitepress/theme/components/LinkPage.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NRow: typeof import('naive-ui')['NRow']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NStatistic: typeof import('naive-ui')['NStatistic']
    PlaygroundWithVariants: typeof import('./.vitepress/theme/components/global/playground/PlaygroundWithVariants.vue')['default']
    SelectorVariants: typeof import('./.vitepress/theme/components/global/playground/SelectorVariants.vue')['default']
    TagsList: typeof import('./.vitepress/theme/components/Tags/TagsList.vue')['default']
    TalkDate: typeof import('./.vitepress/theme/components/TalkDate/index.vue')['default']
    TalkItem: typeof import('./.vitepress/theme/components/Talk/TalkItem.vue')['default']
    TalkList: typeof import('./.vitepress/theme/components/Talk/TalkList.vue')['default']
  }
}
